### ISSUE TITLE
Acceptance Testing: find tag does not work

### ISSUE THREAD

**Issue by arnollim** [CS2103-Phase-B/main#64]
![acceptance testing ft](https://user-images.githubusercontent.com/31108551/32363016-144a9046-c0a8-11e7-8e8a-b0192dace202.png)

Hi T12-B1
Your ft/findtag command is not working

Alex Yeoh is tagged as "friends" but when executing a command, 0 persons are listed

**Comment by adileyzekmoon** [comment]
Sorry about that! We actually removed findtag in favour of filter/filterall but forgot to reflect it in the userguide. Will do so asap
