### ISSUE TITLE
Find Tag

### ISSUE THREAD

**Issue by Estois** [CS2103-Phase-B/main#67]
Findtag function not working.
![image](https://user-images.githubusercontent.com/28403974/32363198-0beb1618-c0a9-11e7-87e3-a602ac5ff414.png)
![image](https://user-images.githubusercontent.com/28403974/32363205-0fb41380-c0a9-11e7-95d5-d0dc5e213ec8.png)
There is also a problem with the userguide, is the keyword find or findtag? 
![image](https://user-images.githubusercontent.com/28403974/32363207-12b1f336-c0a9-11e7-9d38-22fa633f92d7.png)

**Comment by adileyzekmoon** [comment]
fixed
