### ISSUE TITLE
Filter Command Alias

### ISSUE THREAD

**Issue by Estois** [CS2103-Phase-B/main#68]
There is an error in your user guide. Filter all alias is not consistent.
![image](https://user-images.githubusercontent.com/28403974/32363306-a8c5ba1a-c0a9-11e7-8fd0-a671a4faf2d2.png)
Filter alias also not consistent.
![image](https://user-images.githubusercontent.com/28403974/32363323-c2316ddc-c0a9-11e7-8c0c-2c603fc9dee4.png)

**Comment by adileyzekmoon** [comment]
Fixed
