### ISSUE TITLE
Some features updated in User Guide but not in the program?

### ISSUE THREAD

**Issue by arnollim** [CS2103-Phase-B/main#73]
Hi T12-B1
There are a few features that are in the user guide but show "unknown command" upon execution
2.16. Setting up appointment: appointment
2.25. Suggestions as you type
2.26. Autocomplete commands

Are these features only coming up in v2.0?
If so remember to tag feature with TBI in v2.0!

**Comment by AceCentury** [comment]
2.11 and 2.16 in user guide seem to be confusing. Both are also appointment?
